steps:
  - name: hashicorp/terraform:0.13.0
    args:
      - init
      - -backend=true
      - -backend-config=bucket=terraform-upgrade
  - name: hashicorp/terraform:0.13.0
    args:
      - validate
  - name: hashicorp/terraform:0.13.0
    args: ["plan"]